# Generated by Django 3.2.5 on 2021-07-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=255)),
                ('web_page', models.URLField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('est_submissions', models.IntegerField()),
                ('first_day', models.DateTimeField()),
                ('last_day', models.DateTimeField()),
                ('primary_area', models.CharField(max_length=255)),
                ('secondary_area', models.CharField(max_length=250, null=True)),
                ('area_notes', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=100)),
                ('organizer_webpage', models.URLField(max_length=50)),
            ],
        ),
    ]
