# Generated by Django 3.2.5 on 2021-08-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Journal', 'Journal')], max_length=20),
        ),
    ]
