# Generated by Django 3.2.5 on 2021-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_conference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='first_day',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='last_day',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
