# Generated by Django 3.2.5 on 2021-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20210808_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='first_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='last_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='organizer_webpage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='web_page',
            field=models.URLField(),
        ),
    ]
