# Generated by Django 2.2.7 on 2021-08-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20210808_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('paper_title', models.CharField(max_length=255)),
                ('conference', models.ManyToManyField(null=True, to='conference.Conference')),
            ],
        ),
    ]
