# Generated by Django 2.2.7 on 2021-08-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20210810_0323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
