# Generated by Django 3.2.5 on 2021-08-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_delete_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AbstractPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('paper_title', models.CharField(max_length=255)),
                ('abstract_file', models.FileField(upload_to='uploads/')),
                ('conference', models.ManyToManyField(null=True, to='conference.Conference')),
            ],
        ),
    ]
