# Generated by Django 2.2.7 on 2021-08-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auto_20210811_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpaper',
            name='abstract_file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='abstractpaper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
