# Generated by Django 3.2.5 on 2021-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_auto_20210817_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractpaper',
            name='conference',
        ),
        migrations.AddField(
            model_name='abstractpaper',
            name='conference',
            field=models.ManyToManyField(to='conference.Conference'),
        ),
    ]
