# Generated by Django 3.2.5 on 2021-08-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_auto_20210819_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractpaper',
            name='conference',
        ),
        migrations.AddField(
            model_name='abstractpaper',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference'),
        ),
    ]
